# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grace.v1 import grace_pb2 as grace_dot_v1_dot_grace__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grace/v1/grace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReservationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateReservation = channel.unary_unary(
                '/grace.v1.ReservationService/CreateReservation',
                request_serializer=grace_dot_v1_dot_grace__pb2.CreateReservationRequest.SerializeToString,
                response_deserializer=grace_dot_v1_dot_grace__pb2.Reservation.FromString,
                _registered_method=True)
        self.GetReservation = channel.unary_unary(
                '/grace.v1.ReservationService/GetReservation',
                request_serializer=grace_dot_v1_dot_grace__pb2.GetReservationRequest.SerializeToString,
                response_deserializer=grace_dot_v1_dot_grace__pb2.Reservation.FromString,
                _registered_method=True)
        self.ListReservations = channel.unary_unary(
                '/grace.v1.ReservationService/ListReservations',
                request_serializer=grace_dot_v1_dot_grace__pb2.ListReservationsRequest.SerializeToString,
                response_deserializer=grace_dot_v1_dot_grace__pb2.ListReservationsResponse.FromString,
                _registered_method=True)
        self.CancelReservation = channel.unary_unary(
                '/grace.v1.ReservationService/CancelReservation',
                request_serializer=grace_dot_v1_dot_grace__pb2.CancelReservationRequest.SerializeToString,
                response_deserializer=grace_dot_v1_dot_grace__pb2.Reservation.FromString,
                _registered_method=True)
        self.RenewReservation = channel.unary_unary(
                '/grace.v1.ReservationService/RenewReservation',
                request_serializer=grace_dot_v1_dot_grace__pb2.RenewReservationRequest.SerializeToString,
                response_deserializer=grace_dot_v1_dot_grace__pb2.Reservation.FromString,
                _registered_method=True)
        self.ActivateReservation = channel.unary_unary(
                '/grace.v1.ReservationService/ActivateReservation',
                request_serializer=grace_dot_v1_dot_grace__pb2.ActivateReservationRequest.SerializeToString,
                response_deserializer=grace_dot_v1_dot_grace__pb2.Operation.FromString,
                _registered_method=True)
        self.WatchReservation = channel.unary_stream(
                '/grace.v1.ReservationService/WatchReservation',
                request_serializer=grace_dot_v1_dot_grace__pb2.WatchReservationRequest.SerializeToString,
                response_deserializer=grace_dot_v1_dot_grace__pb2.ReservationEvent.FromString,
                _registered_method=True)


class ReservationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReservations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewReservation(self, request, context):
        """The following are specified but explicitly UNIMPLEMENTED in v0.1 runtime.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReservation,
                    request_deserializer=grace_dot_v1_dot_grace__pb2.CreateReservationRequest.FromString,
                    response_serializer=grace_dot_v1_dot_grace__pb2.Reservation.SerializeToString,
            ),
            'GetReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReservation,
                    request_deserializer=grace_dot_v1_dot_grace__pb2.GetReservationRequest.FromString,
                    response_serializer=grace_dot_v1_dot_grace__pb2.Reservation.SerializeToString,
            ),
            'ListReservations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReservations,
                    request_deserializer=grace_dot_v1_dot_grace__pb2.ListReservationsRequest.FromString,
                    response_serializer=grace_dot_v1_dot_grace__pb2.ListReservationsResponse.SerializeToString,
            ),
            'CancelReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelReservation,
                    request_deserializer=grace_dot_v1_dot_grace__pb2.CancelReservationRequest.FromString,
                    response_serializer=grace_dot_v1_dot_grace__pb2.Reservation.SerializeToString,
            ),
            'RenewReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewReservation,
                    request_deserializer=grace_dot_v1_dot_grace__pb2.RenewReservationRequest.FromString,
                    response_serializer=grace_dot_v1_dot_grace__pb2.Reservation.SerializeToString,
            ),
            'ActivateReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateReservation,
                    request_deserializer=grace_dot_v1_dot_grace__pb2.ActivateReservationRequest.FromString,
                    response_serializer=grace_dot_v1_dot_grace__pb2.Operation.SerializeToString,
            ),
            'WatchReservation': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchReservation,
                    request_deserializer=grace_dot_v1_dot_grace__pb2.WatchReservationRequest.FromString,
                    response_serializer=grace_dot_v1_dot_grace__pb2.ReservationEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grace.v1.ReservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grace.v1.ReservationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReservationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grace.v1.ReservationService/CreateReservation',
            grace_dot_v1_dot_grace__pb2.CreateReservationRequest.SerializeToString,
            grace_dot_v1_dot_grace__pb2.Reservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grace.v1.ReservationService/GetReservation',
            grace_dot_v1_dot_grace__pb2.GetReservationRequest.SerializeToString,
            grace_dot_v1_dot_grace__pb2.Reservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grace.v1.ReservationService/ListReservations',
            grace_dot_v1_dot_grace__pb2.ListReservationsRequest.SerializeToString,
            grace_dot_v1_dot_grace__pb2.ListReservationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grace.v1.ReservationService/CancelReservation',
            grace_dot_v1_dot_grace__pb2.CancelReservationRequest.SerializeToString,
            grace_dot_v1_dot_grace__pb2.Reservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grace.v1.ReservationService/RenewReservation',
            grace_dot_v1_dot_grace__pb2.RenewReservationRequest.SerializeToString,
            grace_dot_v1_dot_grace__pb2.Reservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grace.v1.ReservationService/ActivateReservation',
            grace_dot_v1_dot_grace__pb2.ActivateReservationRequest.SerializeToString,
            grace_dot_v1_dot_grace__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grace.v1.ReservationService/WatchReservation',
            grace_dot_v1_dot_grace__pb2.WatchReservationRequest.SerializeToString,
            grace_dot_v1_dot_grace__pb2.ReservationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClusterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterCluster = channel.unary_unary(
                '/grace.v1.ClusterService/RegisterCluster',
                request_serializer=grace_dot_v1_dot_grace__pb2.RegisterClusterRequest.SerializeToString,
                response_deserializer=grace_dot_v1_dot_grace__pb2.ClusterRegistration.FromString,
                _registered_method=True)
        self.ValidateCluster = channel.unary_unary(
                '/grace.v1.ClusterService/ValidateCluster',
                request_serializer=grace_dot_v1_dot_grace__pb2.ValidateClusterRequest.SerializeToString,
                response_deserializer=grace_dot_v1_dot_grace__pb2.Operation.FromString,
                _registered_method=True)
        self.GetCluster = channel.unary_unary(
                '/grace.v1.ClusterService/GetCluster',
                request_serializer=grace_dot_v1_dot_grace__pb2.GetClusterRequest.SerializeToString,
                response_deserializer=grace_dot_v1_dot_grace__pb2.ClusterRegistration.FromString,
                _registered_method=True)


class ClusterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCluster,
                    request_deserializer=grace_dot_v1_dot_grace__pb2.RegisterClusterRequest.FromString,
                    response_serializer=grace_dot_v1_dot_grace__pb2.ClusterRegistration.SerializeToString,
            ),
            'ValidateCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCluster,
                    request_deserializer=grace_dot_v1_dot_grace__pb2.ValidateClusterRequest.FromString,
                    response_serializer=grace_dot_v1_dot_grace__pb2.Operation.SerializeToString,
            ),
            'GetCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCluster,
                    request_deserializer=grace_dot_v1_dot_grace__pb2.GetClusterRequest.FromString,
                    response_serializer=grace_dot_v1_dot_grace__pb2.ClusterRegistration.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grace.v1.ClusterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grace.v1.ClusterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClusterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grace.v1.ClusterService/RegisterCluster',
            grace_dot_v1_dot_grace__pb2.RegisterClusterRequest.SerializeToString,
            grace_dot_v1_dot_grace__pb2.ClusterRegistration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grace.v1.ClusterService/ValidateCluster',
            grace_dot_v1_dot_grace__pb2.ValidateClusterRequest.SerializeToString,
            grace_dot_v1_dot_grace__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grace.v1.ClusterService/GetCluster',
            grace_dot_v1_dot_grace__pb2.GetClusterRequest.SerializeToString,
            grace_dot_v1_dot_grace__pb2.ClusterRegistration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MeteringServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsage = channel.unary_unary(
                '/grace.v1.MeteringService/GetUsage',
                request_serializer=grace_dot_v1_dot_grace__pb2.GetUsageRequest.SerializeToString,
                response_deserializer=grace_dot_v1_dot_grace__pb2.UsageReport.FromString,
                _registered_method=True)


class MeteringServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeteringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsage,
                    request_deserializer=grace_dot_v1_dot_grace__pb2.GetUsageRequest.FromString,
                    response_serializer=grace_dot_v1_dot_grace__pb2.UsageReport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grace.v1.MeteringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grace.v1.MeteringService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeteringService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grace.v1.MeteringService/GetUsage',
            grace_dot_v1_dot_grace__pb2.GetUsageRequest.SerializeToString,
            grace_dot_v1_dot_grace__pb2.UsageReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
